import { z } from "zod";
import { CURRENCIES, parseAmountInput, type Currency } from "@/shared/domain/money";
import { MANUAL_MOVEMENT_TYPES, PAYMENT_METHODS, expectedSign } from "../domain/cash-movement";

const optionalText = z.string().trim().max(300).optional().or(z.literal(""));

/** One counted amount per currency. Blank means nothing of that currency. */
export const currencyCountSchema = z.object({
  currency: z.enum(CURRENCIES),
  amount: z.string().trim().max(30).optional().or(z.literal("")),
});

function checkCounts(
  counts: Array<{ currency: Currency; amount?: string }>,
  ctx: z.RefinementCtx,
): void {
  counts.forEach((count, index) => {
    try {
      const parsed = parseAmountInput(count.amount, count.currency);
      if (parsed?.isNegative()) {
        ctx.addIssue({
          code: "custom",
          path: ["counts", index, "amount"],
          message: "No se puede contar un monto negativo",
        });
      }
    } catch {
      ctx.addIssue({
        code: "custom",
        path: ["counts", index, "amount"],
        message: "Monto inválido",
      });
    }
  });
}

export const openSessionSchema = z
  .object({
    counts: z.array(currencyCountSchema).max(CURRENCIES.length),
    notes: optionalText,
  })
  .superRefine((data, ctx) => checkCounts(data.counts, ctx));

export const closeSessionSchema = z
  .object({
    sessionId: z.string().min(1),
    counts: z.array(currencyCountSchema).max(CURRENCIES.length),
    notes: optionalText,
  })
  .superRefine((data, ctx) => checkCounts(data.counts, ctx));

/**
 * A movement a person types. Sales and repair payments are generated by their
 * own use cases, so they are not offered here.
 */
export const registerMovementSchema = z
  .object({
    type: z.enum(MANUAL_MOVEMENT_TYPES as unknown as [string, ...string[]]),
    /// Always entered as a positive number; the type decides the direction.
    amount: z.string().trim().min(1, "El monto es obligatorio").max(30),
    currency: z.enum(CURRENCIES),
    method: z.enum(PAYMENT_METHODS).default("CASH"),
    description: optionalText,
    /// Adjustments alone may go either way, so they say which.
    direction: z.enum(["IN", "OUT"]).optional(),
  })
  .superRefine((data, ctx) => {
    try {
      const parsed = parseAmountInput(data.amount, data.currency);
      if (!parsed || parsed.isZero()) {
        ctx.addIssue({ code: "custom", path: ["amount"], message: "El monto no puede ser cero" });
      }
      if (parsed?.isNegative()) {
        ctx.addIssue({
          code: "custom",
          path: ["amount"],
          message: "Escribí el monto en positivo y elegí si entra o sale",
        });
      }
    } catch {
      ctx.addIssue({ code: "custom", path: ["amount"], message: "Monto inválido" });
    }

    const type = data.type as (typeof MANUAL_MOVEMENT_TYPES)[number];
    if (expectedSign(type) === "ANY" && !data.direction) {
      ctx.addIssue({
        code: "custom",
        path: ["direction"],
        message: "Elegí si el ajuste suma o resta",
      });
    }
    if (expectedSign(type) === "ANY" && !data.description) {
      ctx.addIssue({
        code: "custom",
        path: ["description"],
        message: "Explicá el motivo del ajuste",
      });
    }
  });

export const payRepairSchema = z
  .object({
    repairId: z.string().min(1),
    amount: z.string().trim().min(1, "El monto es obligatorio").max(30),
    currency: z.enum(CURRENCIES),
    method: z.enum(PAYMENT_METHODS).default("CASH"),
    description: optionalText,
  })
  .superRefine((data, ctx) => {
    try {
      const parsed = parseAmountInput(data.amount, data.currency);
      if (!parsed || !parsed.isPositive()) {
        ctx.addIssue({
          code: "custom",
          path: ["amount"],
          message: "El cobro tiene que ser mayor a cero",
        });
      }
    } catch {
      ctx.addIssue({ code: "custom", path: ["amount"], message: "Monto inválido" });
    }
  });

export const setExchangeRateSchema = z
  .object({
    currency: z.enum(CURRENCIES),
    rate: z.string().trim().min(1, "La cotización es obligatoria").max(30),
  })
  .superRefine((data, ctx) => {
    if (data.currency === "PYG") {
      ctx.addIssue({
        code: "custom",
        path: ["currency"],
        message: "El guaraní es la moneda base y no se cotiza contra sí misma",
      });
    }
    const value = Number(data.rate.replace(/[.\s]/g, "").replace(",", "."));
    if (!Number.isFinite(value) || value <= 0) {
      ctx.addIssue({ code: "custom", path: ["rate"], message: "Cotización inválida" });
    }
  });
